In [1]:
import pandas as pd
import numpy as np

In [2]:
tips = pd.read_csv("https://www.dropbox.com/s/sidhaoro98iej0j/tips.csv?raw=1",index_col=0)
#tips = pd.read_csv("tips.csv",index_col=0)

In [3]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
1       16.99  1.01  Female     No  Sun  Dinner     2
2       10.34  1.66    Male     No  Sun  Dinner     3
3       21.01  3.50    Male     No  Sun  Dinner     3
4       23.68  3.31    Male     No  Sun  Dinner     2
5       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
#不同日期该餐厅顾客总人数和每条账单的平均人数
tips.pivot_table(values='size',index='day',aggfunc = {np.mean,np.sum})

          mean  sum
day
Fri   2.105263   40
Sat   2.517241  219
Sun   2.842105  216
Thur  2.451613  152

In [5]:
#不同时间内男顾客和女顾客的人数
tips.pivot_table(values='size', index=['time'], columns='sex',aggfunc = sum,margins=True)

sex     Female  Male  All
time
Dinner     128   335  463
Lunch       86    78  164
All        214   413  627

In [6]:
#不同性别之间有无吸烟者的账单条数
tips["count"] = 1
tips.pivot_table(values='count', index=['smoker'], columns='sex',aggfunc = sum,margins=True)

sex     Female  Male  All
smoker
No          54    97  151
Yes         33    60   93
All         87   157  244

In [7]:
#该餐厅更受哪类顾客喜爱
tips["satisfication"] = tips["tip"]/tips["total_bill"]
tips.pivot_tab·le(values='satisfication',index=['smoker','sex'])

               satisfication
smoker sex
No     Female       0.156921
       Male         0.160669
Yes    Female       0.182150
       Male         0.152771

In [8]:
tips.describe()

       total_bill         tip        size  count  satisfication
count  244.000000  244.000000  244.000000  244.0     244.000000
mean    19.785943    2.998279    2.569672    1.0       0.160803
std      8.902412    1.383638    0.951100    0.0       0.061072
min      3.070000    1.000000    1.000000    1.0       0.035638
25%     13.347500    2.000000    2.000000    1.0       0.129127
50%     17.795000    2.900000    2.000000    1.0       0.154770
75%     24.127500    3.562500    3.000000    1.0       0.191475
max     50.810000   10.000000    6.000000    1.0       0.710345

In [2]:
import pandas as pd

# 读取CSV文件
tips = pd.read_csv('tips.csv')

In [3]:
time_gender_customers = tips.groupby(['time', 'sex']).size().unstack().reset_index()
time_gender_customers.columns.name = None
time_gender_customers

     time  Female  Male
0  Dinner      52   124
1   Lunch      35    33

In [4]:
gender_smoker_counts = tips.groupby(['sex', 'smoker']).size().unstack().reset_index()
gender_smoker_counts.columns.name = None
gender_smoker_counts

      sex  No  Yes
0  Female  54   33
1    Male  97   60