In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("titanic.csv")

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
df.drop(axis=1,labels=['Cabin'],inplace=True)

In [8]:
df.dropna(axis=0,how="any",inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Pclass       712 non-null    int64
 3   Name         712 non-null    object
 4   Sex          712 non-null    object
 5   Age          712 non-null    float64
 6   SibSp        712 non-null    int64
 7   Parch        712 non-null    int64
 8   Ticket       712 non-null    object
 9   Fare         712 non-null    float64
 10  Embarked     712 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 66.8+ KB

In [13]:
#不同等级船舱男乘客与女乘客的生存率和生存人数
df.pivot_table(values='Survived',index="Sex",columns="Pclass",aggfunc={np.mean,np.sum})

            mean                     sum
Pclass         1         2         3   1   2   3
Sex
female  0.963855  0.918919  0.460784  80  68  47
male    0.396040  0.151515  0.150198  40  15  38

In [16]:
#不同等级船舱乘客平均年龄
df.pivot_table(values='Age',index=["Pclass"],columns="Survived")

Survived          0          1
Pclass
1         43.695312  35.124333
2         33.544444  25.901566
3         26.555556  20.646118

In [52]:
#统计乘客兄弟姐妹个数对于生存率的影响
df.pivot_table(index="SibSp", values="Survived")

       Survived
SibSp
0      0.368870
1      0.530055
2      0.440000
3      0.333333
4      0.166667
5      0.000000

In [17]:
#统计乘客父母小孩个数对于生存率的影响
df.pivot_table(index="Parch", values="Survived")

       Survived
Parch
0      0.354528
1      0.554545
2      0.573529
3      0.600000
4      0.000000
5      0.200000
6      0.000000

In [50]:
#不同等级船舱“18岁以下”“18-45岁”“45岁以上”生存人数
bins = [min(df['Age'])-1, 18, 45, max(df['Age'])]
bins_label = ['18岁及以下', '18-45岁', '45岁以上']
df['Age_cut'] = pd.cut(df['Age'], bins=bins, labels=bins_label)

In [51]:
df.pivot_table(index="Age_cut",values="Survived",columns="Pclass",aggfunc=np.sum)

Pclass    1   2   3
Age_cut
18岁及以下   14  23  33
18-45岁   77  53  51
45岁以上    29   7   1